# Generated by Django 3.2.9 on 2021-12-10 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('heartbeat', models.IntegerField(default=60, help_text='\n            Indica o tempo de processamento máximo desta tarefa.\n            Esse é o tempo que o message broker irá aguardar até que tarefa seja concluída.\n            Caso a tarefa não seja concluída nesse internvalo o message broker irá fechar a conexão com o consumidor\n            e mensagem será marcada para re-envio e processamento.\n            É necessário monitorar o tempo máximo de processamento das tarefas para ajustar \n            adequadamente este intervalo.\n        ')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pool', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='workers.workerpool')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workers.workerqueue')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workers.workertask')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerPoolThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_threads', to='workers.workerpool')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workers.workerthread')),
            ],
        ),
    ]
