# Generated by Django 3.2.9 on 2021-12-13 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workers.integrationitem')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workers.workertask')),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationSourceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_tasks', to='workers.integrationsource')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workers.workertask')),
            ],
        ),
        migrations.AddField(
            model_name='integrationitem',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workers.integrationsource'),
        ),
    ]
