# Generated by Django 3.2.9 on 2021-12-22 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_auto_20211216_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationItemStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('state', models.IntegerField(choices=[(0, 'Pending'), (1, 'Running'), (2, 'Done'), (3, 'Error'), (4, 'Canceled')], default=0)),
                ('create_date', models.DateField()),
                ('init_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('message', models.CharField(max_length=255, null=True)),
                ('details', models.TextField(null=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='integrationstage',
            name='item',
        ),
        migrations.RemoveField(
            model_name='integrationstage',
            name='task',
        ),
        migrations.AddField(
            model_name='integrationitem',
            name='crate_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integrationitem',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='integrationitem',
            name='init_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='integrationitem',
            name='key',
            field=models.CharField(default=None, help_text='\n        Chave única que identifica o item na base de integração. \n        Exemplo: Origem Integracao + Loja + Data Emissao + Modelo + Serie/PDV + Numero NF\n    ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integrationitem',
            name='state',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Running'), (2, 'Done'), (3, 'Error'), (4, 'Canceled')], default=0),
        ),
        migrations.AddField(
            model_name='integrationsourcetask',
            name='sequence',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='integrationsourcetask',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workers.integrationsource'),
        ),
        migrations.AddConstraint(
            model_name='integrationsourcetask',
            constraint=models.UniqueConstraint(fields=('sequence', 'source', 'task'), name='UK_integration_source_task_01'),
        ),
        migrations.DeleteModel(
            name='IntegrationStage',
        ),
        migrations.AddField(
            model_name='integrationitemstage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='workers.integrationitem'),
        ),
        migrations.AddField(
            model_name='integrationitemstage',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workers.workertask'),
        ),
        migrations.AddIndex(
            model_name='integrationitemstage',
            index=models.Index(fields=['state'], name='IDX_integration_stage_01'),
        ),
        migrations.AddConstraint(
            model_name='integrationitemstage',
            constraint=models.UniqueConstraint(fields=('item', 'task', 'sequence'), name='UK_integration_stage_01'),
        ),
    ]
