# Generated by Django 3.2.9 on 2021-12-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_auto_20211222_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='workertask',
            name='module_task',
            field=models.CharField(default='vendas.gera.nota_fiscal_criar.GeraNotaFiscalCriarWorkerTask', max_length=255),
            preserve_default=False,
        ),
    ]
