# Generated by Django 3.2.9 on 2022-01-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_workertask_module_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsource',
            name='code',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='integrationitem',
            name='key',
            field=models.CharField(help_text='\n            Chave única que identifica o item na base de integração. \n            Exemplo: Origem Integracao + Loja + Data Emissao + Modelo + Serie/PDV + Numero NF\n        ', max_length=255),
        ),
    ]
