# Generated by Django 3.2.9 on 2021-12-22 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0004_auto_20211222_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo_sap', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('dia', models.IntegerField()),
                ('modelo', models.CharField(max_length=2)),
                ('serie', models.CharField(max_length=3)),
                ('numero', models.CharField(max_length=9)),
                ('data_emissao', models.DateField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.empresa')),
                ('integracoes', models.ManyToManyField(to='workers.IntegrationItem')),
            ],
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['nome'], name='IDX_empresa_01'),
        ),
        migrations.AddConstraint(
            model_name='empresa',
            constraint=models.UniqueConstraint(fields=('codigo_sap',), name='UK_empresa_01'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['ano'], name='IDX_nota_fiscal_01'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['mes'], name='IDX_nota_fiscal_02'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['dia'], name='IDX_nota_fiscal_03'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['numero'], name='IDX_nota_fiscal_04'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['modelo'], name='IDX_nota_fiscal_05'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['data_emissao'], name='IDX_nota_fiscal_06'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['ano', 'mes', 'dia'], name='IDX_nota_fiscal_07'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['empresa', 'ano', 'mes', 'numero'], name='IDX_nota_fiscal_08'),
        ),
        migrations.AddConstraint(
            model_name='notafiscal',
            constraint=models.UniqueConstraint(fields=('empresa', 'modelo', 'serie', 'numero'), name='UK_nota_fiscal_01'),
        ),
    ]
